backend:
  name: github
  repo: jdow79159/culture-portal
media_folder: static/assets
public_folder: /assets
collections:
  - name: directors
    label: directors
    folder: src/data/directors
    create: true
    fields:
      - { name: lang, label: lang }
      - { name: slug, label: slug }
      - { name: imagepath, label: Image Path, widget: image}
      - { name: type, label: Type }
      - { name: title, label: Title }
      - { name: city, label: City }
      - { name: titleText, label: Title Text }
      - {
          name: directorsLifeYears,
          label: Director's Years of Life,
          widget: string,
        }
      - { name: directorsInfo, label: Director's Info, widget: string }
      - label: Timeline
        name: timeline
        widget: list
        fields:
          - { label: Date, name: date, widget: string }
          - { label: Description, name: description, widget: string }
      - label: List Of Works
        name: listOfWorks
        widget: list
        fields:
          - { label: ID, name: id, widget: string }
          - { label: Year, name: year, widget: string }
          - { label: Film, name: film, widget: string }
      - label: Gallery
        name: gallery
        widget: list
        fields :
          - { label: src, name: src, widget: image }
          - { label: alt, name: alt, widget: string }
      - { label: Youtube, name: youtube, widget: string }
      - label: Geolocation
        name: geolocation
        widget: list
        fields:
          - { label: ID, name: id, widget: string }
          - { label: Latitude, name: latitude, widget: number }
          - { label: Longitude, name: longitude, widget: number }
          - { label: Description, name: description, widget: string }
  - name: pages
    label: pages
    folder: src/data/pages
    create: true
    fields:
      - { name: type, label: type }
      - { name: name, label: name }
      - { name: slug, label: slug }
      - label: fields
        name: fields
        widget: list
        fields:
          -  label: fieldName
             name: fildName
             widget: string
          -  label: fieldData
             name: fieldData
             widget: object
             fields:
               - { label: ru, name: ru, widget: string }
               - { label: be, name: be, widget: string }
               - { label: en, name: en, widget: string }
  - name: navigation
    label: navigation
    folder: src/data/navigation
    create: true
    fields:
      - { name: type, label: type }
      - label: navigations
        name: navigations
        widget: list
        fields:
          - { name: id, label: id, widget: string }
          - label: navigation
            name: navigation
            widget: object
            fields:
              - { label: ru, name: ru , widget: string }
              - { label: be, name: be, widget: string }
              - { label: en, name: en, widget: string }
  - name: developers
    label: developers
    folder: src/data/teammates
    create: true
    fields:
      - {label: lang, name: lang,  widget: string}
      - {label: slug, name: slug,  widget: string}
      - {label: type, name: type,  widget: string}
      - {label: title, name: title,  widget: string}
      - {label: number, name: number,  widget: string}
      - {label: path, name: path,  widget: string}
      - {label: name, name: name,  widget: string}
      - {label: github, name: github,  widget: string}
      - {label: photo, name: photo,  widget: image}
      - {label: role, name: role,  widget: string}
  - name: worklog
    label: worklog
    folder: src/data/worklog
    create: true
    fields:
      - {label: lang, name: lang,  widget: string}
      - {label: slug, name: slug,  widget: string}
      - {label: type, name: type,  widget: string}
      - { name: id, label: id, widget: string }
      - label: works
        name: works
        widget: list
        fields:
          - { label: date, name: date , widget: string }
          - { label: developer, name: developer, widget: string }
          - { label: info, name: info, widget: string }
          - { label: timeSpent, name: timeSpent, widget: string }
      - label: problems
        name: problems
        widget: list
        fields:
          - { label: problem, name: problem , widget: string }
          - { label: solution, name: solution, widget: string }
      - label: selfEvaluation
        name: selfEvaluation
        widget: list
        fields:
          - { label: data, name: data , widget: string }
          - { label: ok, name: ok, widget: string }
      - { label: selfEvaluationSum, name: selfEvaluationSum, widget: string }
